import java.sql.Timestamp;

/**
 * Ticket represents a support ticket in the IT Helpdesk System.
 * It serves as a Model (POJO) that mirrors the 'tickets' table in MySQL.
 */
public class Ticket {

    private int ticketId;
    private String title;
    private String description;
    private String category;
    private String priority;      // LOW, MEDIUM, HIGH, CRITICAL
    private String status;        // OPEN, ASSIGNED, IN_PROGRESS, RESOLVED, CLOSED
    private int employeeId;
    private Integer assignedTo;   // Using Integer wrapper so it can be null (unassigned)
    private Timestamp createdAt;
    private Timestamp updatedAt;

    // Optional helper fields for joined display (Employee and Technician names)
    private String employeeName;
    private String technicianName;

    // Default Constructor
    public Ticket() {
    }

    /**
     * Constructor for creating a NEW ticket (before saving to database).
     * ticketId, status, and timestamps are generated by MySQL.
     */
    public Ticket(String title, String description, String category, String priority, int employeeId) {
        this.title = title;
        this.description = description;
        this.category = category;
        this.priority = priority;
        this.status = "OPEN";
        this.employeeId = employeeId;
        this.assignedTo = null;
    }

    /**
     * Constructor for retrieving an EXISTING ticket from the database.
     */
    public Ticket(int ticketId, String title, String description, String category,
                  String priority, String status, int employeeId, Integer assignedTo,
                  Timestamp createdAt, Timestamp updatedAt) {
        this.ticketId = ticketId;
        this.title = title;
        this.description = description;
        this.category = category;
        this.priority = priority;
        this.status = status;
        this.employeeId = employeeId;
        this.assignedTo = assignedTo;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    // --- Getters and Setters ---

    public int getTicketId() {
        return ticketId;
    }

    public void setTicketId(int ticketId) {
        this.ticketId = ticketId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public int getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }

    public Integer getAssignedTo() {
        return assignedTo;
    }

    public void setAssignedTo(Integer assignedTo) {
        this.assignedTo = assignedTo;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getEmployeeName() {
        return employeeName;
    }

    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    public String getTechnicianName() {
        return technicianName;
    }

    public void setTechnicianName(String technicianName) {
        this.technicianName = technicianName;
    }

    /**
     * Formats ticket details into a clean, human-readable summary.
     */
    @Override
    public String toString() {
        String techDisplay = (technicianName != null) ? technicianName : (assignedTo != null ? "Technician ID: " + assignedTo : "Unassigned");
        String empDisplay = (employeeName != null) ? employeeName : "Employee ID: " + employeeId;

        return String.format(
            "--------------------------------------------------\n" +
            " Ticket #%d: %s\n" +
            "--------------------------------------------------\n" +
            " Category   : %s\n" +
            " Priority   : %s\n" +
            " Status     : %s\n" +
            " Created By : %s\n" +
            " Assigned To: %s\n" +
            " Created At : %s\n" +
            " Updated At : %s\n" +
            " Description:\n   %s\n" +
            "--------------------------------------------------",
            ticketId, title, category, priority, status, empDisplay, techDisplay, createdAt, updatedAt, description
        );
    }
}
